config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pins do
    collection do
      match 'search' => 'pins#search', via: %i[get post], as: :search
    end
  end

  namespace :api do
    namespace :v1 do
      resources :pins
      resources :boards
    end
  end

  resources :boards
  devise_for :users
  root 'home#index'
  get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/pin.rb
# frozen_string_literal: true

class Pin < ApplicationRecord
  belongs_to :user
  belongs_to :board, optional: true
  has_one_attached :image

  # has_attached_file :image, :styles => { :medium =>"300x300>", :thumb =>"100x100>" }
  # validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/controllers/api/v1/pins_controller.rb
# frozen_string_literal: true

class Api::V1::PinsController < ApplicationController
  before_action :set_pin, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show search]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /pins
  # GET /pins.json
  def index
    @q = Pin.order('created_at DESC').ransack(params[:q])
    @pins = @q.result(distinct: true).paginate(page: params[:page], per_page: 20)

    render json: @pins
  end

  # GET /pins/1
  # GET /pins/1.json
  def show; end

  # GET /pins/new
  def new
    @pin = current_user.pins.build

    render json: @pin
  end

  # GET /pins/1/edit
  def edit; end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end

      render json: @pin.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
        render json: @pin
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }

        render json: @pin.errors, status: :unprocessable_entity
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Image was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  def clone
    @newpin = Pin.new
    @newpin.description = @pin.description
    @newpin.image = @pin.image_tag
    @newpin.user = current_user
    @newpin.save
    render :show, status: :ok, location: @newpin
  end

  def search
    index
    render :index
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pin
    @pin = Pin.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pin_params
    params.require(:pin).permit(:description, :image, :board_id)
  end

  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: 'You are not allowed to edit this image' if @pin.nil?
  end
end

app/controllers/pins_controller.rb
# frozen_string_literal: true

class PinsController < ApplicationController
  before_action :set_pin, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show search]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /pins
  # GET /pins.json
  def index
    @q = Pin.order('created_at DESC').ransack(params[:q])
    @pins = @q.result(distinct: true).paginate(page: params[:page], per_page: 20)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show; end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit; end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Image was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Image was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Image was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  def clone
    @newpin = Pin.new
    @newpin.description = @pin.description
    @newpin.image = @pin.image_tag
    @newpin.user = current_user
    @newpin.save
    render :show, status: :ok, location: @newpin
  end

  def search
    index
    render :index
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_pin
    @pin = Pin.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def pin_params
    params.require(:pin).permit(:description, :image, :board_id)
  end

  def correct_user
    @pin = current_user.pins.find_by(id: params[:id])
    redirect_to pins_path, notice: 'You are not allowed to edit this image' if @pin.nil?
  end
end

app/helpers/pins_helper.rb
# frozen_string_literal: true

module PinsHelper
end

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="form-group">
    <%= f.label :image, "Image" %>
    <%= f.file_field :image, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :board, "Choose board" %>
    <option selected><%= f.collection_select(:board_id, current_user.boards, :id, :name, { include_blank: true }, {class: "form-control"}) %></option>
  </div>
  <div class="actions">
    <%= f.submit "Add image", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/pins/edit.html.erb
<h1>Editing image</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="jumbotron">
    <h2 class="center">Images gallery</h2>
    <br />

    <div class="form-inline center">
      <%= search_form_for @q, url: search_pins_path, html: { method: :post } do |f| %>
        <%= f.search_field :description_cont, type: "text", class: "form-control", placeholder: "Search by description " %>

        <%= f.submit 'Search', class:"btn btn-default"%>
    <% end %>
  </div>
        
    <%= link_to 'Add image', new_pin_path, class: 'btn btn-primary' %> <br/><br/>
    <div class="masonry">
        <% @pins.each do |pin| %>
          <div class="item">
              <%= link_to pin_path(pin) do %>
                <%= image_tag url_for (pin.image) %>
              <% end %>
          </div>
        <% end %>
    </div>
  </div>
</div> 
<div class="center paginate">
  <%= will_paginate @pins, :previous_label => 'Previous page', :next_label => "Next page", renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>Add new image</h1>

<%= render 'form', pin: @pin %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <div id="show_image"><%= image_tag @pin.image %>
</p>
<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>
<br />

<% if @pin.user == current_user %>
  <%= link_to 'Edit', edit_pin_path(@pin), class: 'btn btn-primary btn-sm' %>
  <%= link_to 'Delete', @pin, method: :delete, data: { confirm: 'Czy na pewno usunąć?' }, class: 'btn btn-primary btn-sm' %>
<% end %>




<%= link_to 'Back', pins_path, class: 'btn btn-primary btn-sm'%>
<br/>
<br/>
<br/>

<% if @pin.image.attached? %>


<!-- @post.image.present? will always return true, use attached? to check presence -->

<% end %>