config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pins do
    collection do
      match 'search' => 'pins#search', via: %i[get post], as: :search
    end
  end

  namespace :api do
    namespace :v1 do
      resources :pins
      resources :boards
    end
  end

  resources :boards
  devise_for :users
  root 'home#index'
  get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end

  def about; end
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/views/home/_footer.html.erb
<footer class="footer">
  <div class="container">
    <p>PixDream 2018</p>  
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'PixDream', root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Main', root_path%></li>
        <li><%= link_to 'About', home_about_path %></li>
        <li><%= link_to 'Images gallery', pins_path %></li>

        <% if user_signed_in? %>
        <li><%= link_to 'My boards', boards_path %></li>
        <li><%= link_to 'Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/home/about.html.erb
<h1>About</h1>
<br />
<p>PixDream is a place to store and share imges. You can upload pictures and share them with other users.<br>
   Add your own images and organize them into collections - keep your ideas and inspirations in one place. :)</p>
<br />
<br />
<br />
<p>PixDream app is final project on my postgraduate studies of Web application programing 2017/2018 at AGH University of Science and Technology.<br />
   Application was inspired by websites and social network like Pinterest and We Heart It.</p>

app/views/home/index.html.erb
<div class="container">
    <!-- Carousel
    ================================================== -->
  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <div class="first-slide"><%= image_tag  "app_images/1.jpg" %></div>
        <div class="container">
          <div class="carousel-caption">
            <h1>Welcome to PixDream app!</h1>
            <p>Click below to start</p>
            <p><%= link_to 'Sign in', new_user_session_path, class: 'btn btn-primary' %></p>
          </div>
        </div>
      </div>
      <div class="item">
        <div class="second-slide"><%= image_tag  "app_images/2.jpg" %></div>
        <div class="container">
          <div class="carousel-caption">
            <h1>Look for inspirations</h1>
            <p>See gallery of available images</p>
            <p><%= link_to 'Images gallery', pins_path, class: 'btn btn-primary' %></p>
          </div>
        </div>
      </div>
      <div class="item">
        <div class="third-slide"><%= image_tag  "app_images/3.jpg" %></div>
        <div class="container">
          <div class="carousel-caption">
            <h1>Add images and share your ideas</h1>
            <p>Click below to start adding new images</p>
            <p><%= link_to 'Add image', new_pin_path, class: 'btn btn-primary' %></p>
          </div>
        </div>
      </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div><!-- /.carousel -->
</div>