config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :pins do
    collection do
      match 'search' => 'pins#search', via: %i[get post], as: :search
    end
  end

  namespace :api do
    namespace :v1 do
      resources :pins
      resources :boards
    end
  end

  resources :boards
  devise_for :users
  root 'home#index'
  get 'home/about'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/board.rb
# frozen_string_literal: true

class Board < ApplicationRecord
  belongs_to :user
  has_many :pins
end

app/controllers/api/v1/boards_controller.rb
# frozen_string_literal: true

class Api::V1::BoardsController < ApplicationController
  before_action :set_board, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = current_user.boards
                          .order('created_at DESC')
                          .paginate(page: params[:page], per_page: 9)
    render json: @boards
  end

  # GET /boards/1
  # GET /pboards/1.json
  def show
    @board_pins = @board.pins
                        .order('created_at DESC')
                        .paginate(page: params[:page], per_page: 9)
    render json: @board
  end

  # GET /boards/new
  def new
    @board = current_user.boards.build
    render json: @board
  end

  # GET /boards/1/edit
  def edit; end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.build(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Tablica została pomyślnie dodana.' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }

        render json: @board.errors, status: :unprocessable_entity
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Tablica została pomyślnie zmieniona' }
        format.json { render :show, status: :ok, location: @board }
        render json: @board
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
        render json: @board.errors, status: :unprocessable_entity
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Tablica została pomyślnie usunięta.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def board_params
    params.require(:board).permit(:description, :name, :image)
  end

  def correct_user
    @board = current_user.boards.find_by(id: params[:id])
    redirect_to boards_path, notice: 'Nie jesteś uprawiony do edycji tej tablicy' if @board.nil?
  end
end

app/controllers/boards_controller.rb
# frozen_string_literal: true

class BoardsController < ApplicationController
  before_action :set_board, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :correct_user, only: %i[edit update destroy]

  # GET /boards
  # GET /boards.json
  def index
    @boards = current_user.boards
                          .order('created_at DESC')
                          .paginate(page: params[:page], per_page: 9)
  end

  # GET /boards/1
  # GET /pboards/1.json
  def show
    @board_pins = @board.pins
                        .order('created_at DESC')
                        .paginate(page: params[:page], per_page: 9)
  end

  # GET /boards/new
  def new
    @board = current_user.boards.build
  end

  # GET /boards/1/edit
  def edit; end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.build(board_params)

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created' }
        format.json { render :show, status: :created, location: @board }
      else
        format.html { render :new }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boards/1
  # PATCH/PUT /boards/1.json
  def update
    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board.destroy
    respond_to do |format|
      format.html { redirect_to boards_url, notice: 'Board was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_board
    @board = Board.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def board_params
    params.require(:board).permit(:description, :name, :image)
  end

  def correct_user
    @board = current_user.boards.find_by(id: params[:id])
    redirect_to boards_path, notice: 'Nie jesteś uprawiony do edycji tej tablicy' if @board.nil?
  end
end

app/views/boards/_form.html.erb
<%= form_for @board, html: { multipart: true } do |f| %>
  <% if @board.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@board.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @board.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Board_name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Save board", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/boards/edit.html.erb
<h1>Editing Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Show', @board %> |
<%= link_to 'Back', board_path %>

app/views/boards/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="jumbotron">
    <h2 class="center">My images collections</h2>
    <%= link_to 'New board', new_board_path, class: 'btn btn-primary' %> <br/><br/>

    <div class="row">
      <% @boards.each do |board| %>
        <div class="col-md-4">
          <div class="thumbnail">
            <div class="caption">
              <h4><%=board.name %></h4>
              <p><%= link_to 'Show board', board, class: 'btn btn-primary btn-sm'%></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>


<div class="center">
 <%= will_paginate @boards, :previous_label => 'Poprzednia strona', :next_label => "Następna strona", renderer: BootstrapPagination::Rails %></div>

app/views/boards/new.html.erb
<h1>New Board</h1>

<%= render 'form', board: @board %>

<%= link_to 'Back', boards_path %>

app/views/boards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @board.description %>
</p>

<p>
  <%= link_to 'Edit', edit_board_path(@board), class: 'btn btn-primary btn-sm' %>
  <%= link_to 'Delete', @board, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm' %>
  <%= link_to 'Back', boards_path, class: 'btn btn-primary btn-sm'%>
</p>


<div class="continer">
  <div class="jumbotron">
    <p class="center">
      <strong>Images in your board:</strong><br /><br />
      <%= link_to 'Add image', new_pin_path, class: 'btn btn-primary btn-sm' %> <br/><br/>
    </p>

    <div class="row">
        <% @board_pins.each do |board_pin| %>
          <div class="col-md-4">
            <div class="thumbnail-boards">
              <br />
              <%= link_to pin_path(board_pin) do %>
                <%= image_tag url_for (board_pin.image) %>
              <% end %>
            </div>
          </div>
        <% end %>
    </div>
  </div>
</div>
<div class="center">
  <%= will_paginate @board_pins, renderer: BootstrapPagination::Rails %>
</div>